apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  destination:
    namespace: test
    server: https://kubernetes.default.svc
  project: default
  source:
    path: test-ingress
    repoURL: https://github.com/AnkitCubastion/test-deployment.git
    targetRevision: main
