apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-react-app
spec:
  destination:
    namespace: test
    server: https://kubernetes.default.svc
  project: default
  source:
    path: test-react-app
    repoURL: https://github.com/AnkitCubastion/test-deployment.git
    targetRevision: main
