apiVersion: v1
kind: Service
metadata:
  name: test-node-app
  namespace: test
spec:
  selector:
    app.kubernetes.io/name: test-node-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
