apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-db
  namespace: test
  labels:
    app: test-db
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: test-db
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: test-db
    spec:
      containers:
        - name: test-db
          image: "10.0.0.34:8082/test-images/test-db:1.0"
          imagePullPolicy: Always
          ports:
            - containerPort: 3306
          envFrom:
            - configMapRef:
                name: test-db
      imagePullSecrets:
        - name: harbor-pull-secret
